[package]
name = "jamespy"
version = "0.2.0"
edition = "2021"

[dependencies]
jamespy_data = { path = "jamespy_data" }
jamespy_events = { path = "jamespy_events" }
jamespy_config = { path = "jamespy_config" }
jamespy_commands = { path = "jamespy_commands" }

serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next" }
poise = { git = "https://github.com/serenity-rs/poise", branch = "serenity-next" }
#serenity = { path = "../serenity" }



tokio = { version = "1.33.0", features = ["macros", "signal", "rt-multi-thread", "net", "io-util"] }
sqlx = { version = "0.7.1", features = ["macros", "runtime-tokio-rustls", "postgres", "time", "chrono"] }
dashmap = "5.5.3"
rand = "0.8.5"
bb8-redis = "0.13.1"
reqwest = "0.11.23"

tracing-subscriber = "0.3.18"
tracing = "0.1.40"


[workspace]
members = [ "jamespy_config", "jamespy_data", "jamespy_events", "jamespy_config", "jamespy_commands"]



[profile.release]
strip = true
opt-level = "z" # opt for size
lto = true
codegen-units = 1
