[package]
name = "jamespy"
version = "0.1.2-rc1"
edition = "2021"

[dependencies]
jamespy_utils = { path = "jamespy_utils" }
jamespy_data = { path = "jamespy_data" }
jamespy_config = { path = "jamespy_config" }
jamespy_events = { path = "jamespy_events" }


serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next" }
poise = { git = "https://github.com/serenity-rs/poise", branch = "serenity-next" }
#serenity = { path = "../serenity" }



tokio = { version = "1.33.0", features = ["macros", "signal", "rt-multi-thread", "net", "io-util"] }
sqlx = { version = "0.7.1", features = ["macros", "runtime-tokio-rustls", "postgres", "time", "chrono"] }
rand = "0.8.5"
serde = "1.0.192"
serde_json = "1.0.108"
regex = "1.9.3"
bb8-redis = "0.13.1"
reqwest = "0.11.23"
chrono = "0.4.28"
base64 = "0.21.5"
fs_extra = "1.3.0"

tracing-subscriber = "0.3.18"
tracing = "0.1.40"

dashmap = "5.5.3"

[workspace]
members = [
    "jamespy_utils",
    "jamespy_data",
    "jamespy_config",
    "jamespy_events"
]



[profile.release]
strip = true
opt-level = "z" # opt for size
lto = true
codegen-units = 1
