[package]
name = "jamespy"
version = "0.2.0"
edition = "2021"

[dependencies]
jamespy_data = { path = "jamespy_data" }
jamespy_events = { path = "jamespy_events" }
jamespy_config = { path = "jamespy_config" }
jamespy_commands = { path = "jamespy_commands" }

sqlx = { workspace = true }
tokio = { workspace = true }
poise = { workspace = true }
serenity = { workspace = true }
reqwest = { workspace = true }
songbird = { workspace = true }
parking_lot = { workspace = true }
dashmap = { workspace = true }

tracing-subscriber = "0.3.18"

symphonia = { features = ["aac", "mp3", "isomp4", "alac"], version = "0.5.2" }


[workspace]
members = [ "jamespy_config", "jamespy_data", "jamespy_events", "jamespy_config", "jamespy_commands"]

[workspace.dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "signal", "parking_lot"] }
sqlx = { version = "0.7", features = ["macros", "postgres", "runtime-tokio-rustls", "chrono"] }
bb8-redis = "0.13"
reqwest = "0.12"
rand = "0.8"
small-fixed-array = "0.4"
chrono = "0.4"
parking_lot = "0.12.1"
dashmap = "5.5.3"

[workspace.dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
#path = "../serenity"
features = ["temp_cache"]
default-features = false
branch = "next"



[workspace.dependencies.poise]
git = "https://github.com/serenity-rs/poise"
features = ["cache"]
branch = "serenity-next"

[workspace.dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
features = ["builtin-queue"]
branch = "serenity-next"

# patch for developing locally.
#[patch."https://github.com/serenity-rs/serenity".serenity]
#path = "../serenity"


[profile.release]
strip = true
opt-level = "z" # opt for size
lto = true
codegen-units = 1
