[package]
name = "jamespy-rs"
version = "0.1.1"
edition = "2021"

[dependencies]
poise = { git = "https://github.com/serenity-rs/poise", branch = "current" }
tokio = { version = "1.33.0", features = ["macros", "signal", "rt-multi-thread", "net", "io-util"] }
futures-util = { version = "0.3.28", default-features = false, features = ["sink", "std"] }
futures-channel = "0.3.28"
sqlx = { version = "0.7.1", features = ["macros", "runtime-tokio-rustls", "postgres", "time", "chrono"] }
rand = "0.8.5"
reqwest = "0.11.18"
serde = "1.0.192"
openssl = { version = "0.10", features = ["vendored"] } # for cross compiling
bb8-redis = "0.13.1"
toml = "0.8.0"
regex = "1.9.3"
lazy_static = "1.4.0"
chrono = "0.4.28"
serde_json = "1.0.108"
# Optional dependencies
tokio-tungstenite = { version = "0.20", features = ["rustls-tls-native-roots"], optional = true  }
typesize = { version = "0.1.2", features = ["url", "time", "serde_json", "secrecy", "dashmap", "parking_lot", "details"] }

# serenity patch for developing.
#[patch.'https://github.com/serenity-rs/serenity']
#serenity = { git = 'https://github.com//serenity-rs/serenity', branch = 'next' }



[dependencies.serenity]
features = ["unstable_discord_api", "typesize"]
default-features = false
version = "0.12"

[features]
websocket = ["tokio-tungstenite"]

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1
