[package]
name = "jamespy-rs"
version = "0.1.1"
edition = "2021"

[dependencies]
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next" }
poise = { git = "https://github.com/serenity-rs/poise", branch = "serenity-next" }
#serenity = { path = "../serenity" }



tokio = { version = "1.33.0", features = ["macros", "signal", "rt-multi-thread", "net", "io-util"] }
futures-util = { version = "0.3.28", default-features = false, features = ["sink", "std"] }
futures-channel = "0.3.28"
sqlx = { version = "0.7.1", features = ["macros", "runtime-tokio-rustls", "postgres", "time", "chrono"] }
rand = "0.8.5"
reqwest = "0.11.18"
serde = "1.0.192"
openssl = { version = "0.10", features = ["vendored"] } # for cross compiling
bb8-redis = "0.13.1"
regex = "1.9.3"
lazy_static = "1.4.0"
chrono = "0.4.28"
serde_json = "1.0.108"
base64 = "0.21.5"

# Optional dependencies
fs_extra = "1.3.0"
dashmap = "5.5.3"
tracing-subscriber = "0.3.18"
tracing = "0.1.40"



[patch.crates-io]

[features]
castle = []

[profile.release]
strip = true
opt-level = "z" # opt for size
lto = true
codegen-units = 1
