[package]
name = "jamespy_commands"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jamespy_data = { path = "../jamespy_data" }
jamespy_events = { path = "../jamespy_events" }
jamespy_config = { path = "../jamespy_config" }

serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next" }
poise = { git = "https://github.com/serenity-rs/poise", branch = "serenity-next" }
#serenity = { path = "../serenity" }

sqlx = { version = "0.7.1", features = ["macros", "runtime-tokio-rustls", "postgres", "time", "chrono"] }
rand = "0.8.5"
bb8-redis = "0.13.1"
reqwest = "0.11.23"

tracing-subscriber = "0.3.18"
tracing = "0.1.40"
small-fixed-array = "0.4.0"
libc = "0.2.152"
sysinfo = "0.30.5"
regex = "1.10.3"
