[package]
name = "jamespy_starboard"
version = "0.1.0"
edition = "2024"

[dependencies]
jamespy_data = { path = "../jamespy_data" }
poise.workspace = true
regex.workspace = true
serenity.workspace = true
small-fixed-array.workspace = true
