[package]
name = "jamespy_filter"
version = "0.1.0"
edition = "2024"

[dependencies]
jamespy_ansi = { path = "../jamespy_ansi" }
regex.workspace = true
rustrict.workspace = true
serenity.workspace = true

