[package]
name = "jamespy_websocket"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"
futures-channel = "0.3.30"
futures-util = "0.3.30"
serde = "1.0.203"
serde_json = "1.0.120"
serenity.workspace = true
tokio.workspace = true
tokio-tungstenite = "0.23.1"
